meta_product_name: "Adept"
meta_title: "Adept - A Community Driven Solution for an Inclusive Future"
meta_description: "An app allowing users to filter venues according to specific accessibility requirements"
meta_image: "adept-master-image.png"
